############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "/about/"
weight = 3

[[main]]
name = "Blog"
url = "/blog/"
weight = 2

# footer menu
[[footer]]
name = "About Me"
url = "/about/"
weight = 1

[[footer]]
name = "Blog"
url = "/blog/"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4
